---
- name: Install WireGuard
  become: true
  tags: wireguard
  block:
    - name: Install
      apt:
        name:
          - wireguard
          - openresolv
        update_cache: true

    - name: Generate keys
      shell: |
        set -o pipefail
        umask 077
        wg genkey | tee private.key | wg pubkey > public.key
      args:
        chdir: /etc/wireguard
        creates: /etc/wireguard/private.key
        executable: /bin/bash
      register: wireguard_keys

    - name: Read public key
      command: cat /etc/wireguard/public.key
      register: wireguard_public_key
      changed_when: false

    - name: Print to console
      debug:
        var: wireguard_public_key.stdout

    - name: Configure interfaces
      template:
        dest: /etc/wireguard/{{ interface.key }}.conf
        src: interface.conf.j2
        mode: '0600'
      loop: "{{ wireguard_interfaces | dict2items }}"
      loop_control:
        loop_var: interface
        label: interface_{{ interface.key }}
      register: wireguard_interfaces_configured
      notify: Restart Wireguard

    - name: Configure services
      service:
        name: wg-quick@{{ interface.key }}
        state: "{{ interface.value.state | default('started') }}"
        enabled: "{{ interface.value.enabled | default(true) }}"
      loop: "{{ wireguard_interfaces | dict2items }}"
      loop_control:
        loop_var: interface
        label: interface_{{ interface.key }}
